### ISSUE TITLE
Middleware usage

### ISSUE THREAD

**Issue by uxkjaer** [mattreid1/baojs#2]
Exciting new project you have here. I'm experimenting with bun.sh atm and are trying to use baojs to replace express with bao. I have some dependencies in my node_modules ie [ui5-tooling](https://sap.github.io/ui5-tooling/) that runs an express server. 
I'm trying to run some express middlewares through bao and have hacked the ui5 cli a bit to use bao instead. I understand that bao doesn't use app.use, but I need to specify a specific mountpath for my middleware. Is this something that is currently supported?
The issue is [here](https://github.com/SAP/ui5-server/blob/master/lib/middleware/MiddlewareManager.js#L42)

**Comment by avmentzer** [comment]
Great works so far! How to parse ejs templates? How to pass form-data?

**Comment by uxkjaer** [comment]
I'm thinking of writing a new bao server for ui5 instead of trying to hack the existing. I should be able to reuse some stuff from the tooling to read the middleware modules through the middleware manager and use the hooks in bao to serve them. Next up is serving local resources. I'll update more later if I have issues.

**Comment by mattreid1** [comment]
So middleware currently works by explicitly stating if it's to be run before or after the routes, e.g.

```typescript
// Runs before the routes to add some extra data
app.before((ctx) => {
  ctx.extra.abc = 123;
  return ctx;
});
```

Which could also be written as 

```typescript
function addAbc(ctx: Context) {
  ctx.extra.abc = 123;
  return ctx;
}

app.before(addAbc);
```

I'm not sure if you need anything else from my end, but if you do please let me know!

**Comment by mattreid1** [comment]
I'm going to close this as I haven't heard anything for a couple of weeks, feel free to reopen if you have any issues!
