### ISSUE TITLE
Your claim of 2.5x increase in HTTP request throughput links to a dead page (404)

### ISSUE THREAD

**Issue by PiotrOwsiak** [mattreid1/baojs#24]
This section of your README points to non existing page that is supposed to support the 2.5x claim:

Bun was released as a fast, modern JavaScript runtime. One of the many improvements over Node.js was the 2.5x increase in HTTP request throughput when compared to the Node.js http module ([reference](https://github.com/Jarred-Sumner/bun/blob/7d1c9fa1a471d180c078a860c4885478f334bdf5/README.md#bunserve---fast-http-server)).

**Comment by mattreid1** [comment]
https://github.com/oven-sh/bun/blob/7d1c9fa1a471d180c078a860c4885478f334bdf5/README.md
