### ISSUE TITLE
Benchmarks: add Fastify

### ISSUE THREAD

**Issue by matschik** [mattreid1/baojs#3]
Comparing baojs to express is quite unfair since Fastify is the fastest framework.
Better compare to Fastify than Express.

**Comment by micalevisk** [comment]
indeed.

Here's the equivalent code @mattreid1:

```js
const fastify = require('fastify');
const Etag = require('@fastify/etag');
const app = fastify({ logger: false });
app.register(Etag);

app.get('/', () => 'OK');
app.listen({ port: 5000 });
```

`express` generates the `etag` header by default, not sure about Baojs. Maybe ins't fair to use the above code as the `@fastify/etag` plugin doesn't use the same algorithm. I guess it's better to disable the etag generation on both snippets

**Comment by tomByrer** [comment]
I did find one blog post from 7 months ago that compared Fastify vs Express, showing only a 20% difference, but I suspect the Nginx reverse proxy may have changed the results?

https://medium.com/@onufrienkos/express-vs-fastify-performance-4dd5d73e08e2

**Comment by mattreid1** [comment]
I added the benchmark and It turns out that it's about equal. It would be awesome if we could get it even faster though! I didn't add the Etag as Bao doesn't have that just yet (will probably be done using middleware in the future).
